{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "acm-switchover.fullname" . }}
  namespace: {{ .Values.rbac.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "acm-switchover.fullname" . }}
    namespace: {{ .Values.rbac.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "acm-switchover.fullname" . }}
{{- end }}
