apiVersion: v1
kind: Service
metadata:
  name: acm-switchover-api
  labels:
    app: acm-switchover-api
spec:
  selector:
    app: acm-switchover-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
